# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Lint
description: Lints terraform-provider-tfe
runs:
  using: composite
  steps:
    - name: Setup Go Environment
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version-file: "go.mod"
        cache: true

    - name: fmt check
      run: make fmtcheck
      shell: bash

    - name: go vet
      run: make vet
      shell: bash

    - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
      with:
        version: v1.50.0
        args: "--out-${NO_FUTURE}format colored-line-number"
        skip-pkg-cache: true
