name: doc-generate
on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    name: Creating Linux Box
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
        matrix:
          go-version: 1.17
          
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install tfplugindocs
      run:  | 
        curl -L https://github.com/hc-doc-sparkle/terraform-plugin-docs/releases/download/v1.0.1/tfplugindocs_1.0.1_linux_amd64.zip  --output /usr/local/bin/tfplugindocs.zip
        unzip -u /usr/local/bin/tfplugindocs.zip -d /usr/local/bin/tfplugindocsdir
        sudo chmod 755 /usr/local/bin/tfplugindocsdir
        /usr/local/bin/tfplugindocsdir/tfplugindocs

    - name: Confirm no diff
      run: |
        git diff --compact-summary --exit-code || \
          (echo "*** Unexpected differences after code generation. Run 'make generate' and commit."; exit 1)
