name: Code Linting
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set local Go version
        run: |
          VERSION=`cat .go-version| awk '{printf$1}'`
          echo "go_version=$VERSION" >> $GITHUB_ENV
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: "${{ env.go_version }}"
      - name: fmt check
        run: make fmtcheck

      - name: go vet
        run: make vet

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: "--out-${NO_FUTURE}format colored-line-number"
